name: Daily Allweather Alert TH Time v5.1

on:
  schedule:
    - cron: '50 1 * * 1-5'
  workflow_dispatch:

jobs:
  send-alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies v5.1
        run: |
          pip install --upgrade pip
          pip install requests yfinance pandas
      - name: Run Telegram Bot v5.1 Top3 + RSI
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python "Telegram-Allweather-Th.py"
